// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_titles from "./routes/api/titles.ts";
import * as $index from "./routes/index.tsx";
import * as $title_title_ from "./routes/title/[title].tsx";
import * as $title_index from "./routes/title/index.tsx";
import * as $Chart from "./islands/Chart.tsx";
import * as $SortableTable from "./islands/SortableTable.tsx";
import * as $TitlesTable from "./islands/TitlesTable.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/titles.ts": $api_titles,
    "./routes/index.tsx": $index,
    "./routes/title/[title].tsx": $title_title_,
    "./routes/title/index.tsx": $title_index,
  },
  islands: {
    "./islands/Chart.tsx": $Chart,
    "./islands/SortableTable.tsx": $SortableTable,
    "./islands/TitlesTable.tsx": $TitlesTable,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
